apiVersion: 1

datasources:
  - name: traffic-clickhouse
    uid: traffic_clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      server: clickhouse
      port: 8123
      protocol: http
      username: airflow
      defaultDatabase: traffic_db
      tlsSkipVerify: true
    secureJsonData:
      password: airflow